### ISSUE TITLE
make gtk-gresource script

### ISSUE THREAD

**Issue by Elbullazul** [bluedxca93/aero-experimental#3]
@bluedxca93 I don't remember where you asked me for this, so I'll post it here

here's the script to convert existing theme to gtk.gresource (gtk 3.0 and 3.20)

https://github.com/B00merang-Project/Shell-Scripts/blob/master/gtk-compile

**Comment by bluedxca93** [comment]
Hi, yes i get now the idea of how its done. Once ive the time i ll test it.
seems to be very good.
